repositoryUrl: https://github.com/gsmlg-dev/caddy-dns-zdns.git
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@semantic-release/exec"
    - "prepareCmd": >-
        echo ${nextRelease.version};
        go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest;
        xcaddy build v2.6.2 --output ./caddy --with github.com/gsmlg-dev/caddy-dns-zdns=$(pwd);
      "publishCmd": "echo publish caddy-dns-zdns ${nextRelease.version}"
branches:
  - +([0-9])?(.{+([0-9]),x}).x
  - main
  - next
  - next-major
  - { name: "beta", prerelease: true }
  - { name: "alpha", prerelease: true }
